service: event-bridge-sqs-demo

frameworkVersion: "3"

plugins:
  - serverless-apigateway-service-proxy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: events:PutEvents
          Resource: !GetAtt EventBus.Arn

custom:
  apiGatewayServiceProxies:
    - eventbridge: # source and detailType are hardcoded; detail defaults to POST body
        path: /eventbridge
        method: post
        source: "fuel-app"
        detailType: "user-signup"
        eventBusName: { Ref: "EventBus" }
        cors: true

functions:
  putEventsLambda:
    handler: functions/putEvents.handler
    events:
      - http:
          path: /generate
          method: post
    environment:
      EventBusName: !Ref EventBus
  processEventLambda:
    handler: functions/processEvent.handler
    events:
      - sqs:
          arn: !GetAtt TargetSQS.Arn
          batchSize: 10
          functionResponseType: "ReportBatchItemFailures"

resources:
  Resources: ${file(resources.yml)}
  Outputs:
    EventBusName:
      Value: !Ref EventBus
